export const FIELDS_SEED = [
  {
    name: 'Artificial Intelligence / Machine Learning',
    description: 'Build and train AI models, neural networks, and intelligent systems',
    icon_emoji: '🤖',
    color_class: 'bg-purple-50 border-purple-200 hover:border-purple-400',
    keywords: [
      'machine learning', 'deep learning', 'neural networks', 'PyTorch', 'TensorFlow',
      'LLM', 'transformer', 'NLP', 'computer vision', 'reinforcement learning',
      'scikit-learn', 'MLOps', 'model training', 'AI engineer', 'data pipeline',
    ],
  },
  {
    name: 'Software Engineering',
    description: 'Design, develop and maintain software systems and applications',
    icon_emoji: '💻',
    color_class: 'bg-blue-50 border-blue-200 hover:border-blue-400',
    keywords: [
      'software engineer', 'backend', 'frontend', 'full stack', 'API design',
      'microservices', 'system design', 'algorithms', 'data structures', 'Java',
      'Python', 'Go', 'distributed systems', 'REST', 'gRPC',
    ],
  },
  {
    name: 'Data Science & Analytics',
    description: 'Extract insights from data using statistics, analytics, and visualization',
    icon_emoji: '📊',
    color_class: 'bg-green-50 border-green-200 hover:border-green-400',
    keywords: [
      'data scientist', 'data analyst', 'Python', 'R', 'SQL', 'pandas',
      'data visualization', 'Tableau', 'Power BI', 'statistics', 'A/B testing',
      'Spark', 'Snowflake', 'dbt', 'ETL', 'business intelligence',
    ],
  },
  {
    name: 'Cybersecurity',
    description: 'Protect systems, networks, and data from digital attacks',
    icon_emoji: '🔒',
    color_class: 'bg-red-50 border-red-200 hover:border-red-400',
    keywords: [
      'cybersecurity', 'penetration testing', 'security engineer', 'SIEM', 'SOC',
      'vulnerability assessment', 'incident response', 'network security', 'CISSP',
      'zero trust', 'cloud security', 'compliance', 'threat intelligence', 'malware analysis',
    ],
  },
  {
    name: 'Cloud Computing & DevOps',
    description: 'Build and manage scalable cloud infrastructure and CI/CD pipelines',
    icon_emoji: '☁️',
    color_class: 'bg-sky-50 border-sky-200 hover:border-sky-400',
    keywords: [
      'AWS', 'Azure', 'GCP', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD',
      'DevOps engineer', 'SRE', 'infrastructure as code', 'Helm', 'GitOps',
      'observability', 'Linux', 'cloud architect',
    ],
  },
  {
    name: 'Product Management',
    description: 'Define product vision, strategy, and roadmap to deliver user value',
    icon_emoji: '📋',
    color_class: 'bg-orange-50 border-orange-200 hover:border-orange-400',
    keywords: [
      'product manager', 'product roadmap', 'agile', 'scrum', 'user stories',
      'OKRs', 'go-to-market', 'stakeholder management', 'product strategy',
      'Jira', 'product analytics', 'user research', 'PRD', 'sprint planning',
    ],
  },
  {
    name: 'UX/UI Design',
    description: 'Create intuitive, beautiful user experiences and interfaces',
    icon_emoji: '🎨',
    color_class: 'bg-pink-50 border-pink-200 hover:border-pink-400',
    keywords: [
      'UX designer', 'UI designer', 'Figma', 'user research', 'wireframing',
      'prototyping', 'design systems', 'accessibility', 'usability testing',
      'interaction design', 'information architecture', 'Adobe XD', 'design thinking',
    ],
  },
  {
    name: 'Full-Stack Web Development',
    description: 'Build complete web applications from frontend to backend',
    icon_emoji: '🌐',
    color_class: 'bg-teal-50 border-teal-200 hover:border-teal-400',
    keywords: [
      'React', 'Next.js', 'TypeScript', 'Node.js', 'full stack developer',
      'PostgreSQL', 'MongoDB', 'GraphQL', 'REST API', 'CSS', 'Tailwind',
      'Vue.js', 'web performance', 'authentication', 'deployment',
    ],
  },
  {
    name: 'Mobile App Development',
    description: 'Build native and cross-platform mobile applications',
    icon_emoji: '📱',
    color_class: 'bg-indigo-50 border-indigo-200 hover:border-indigo-400',
    keywords: [
      'iOS developer', 'Android developer', 'React Native', 'Flutter', 'Swift',
      'Kotlin', 'mobile UI', 'App Store', 'Google Play', 'push notifications',
      'offline storage', 'mobile performance', 'Expo', 'cross-platform',
    ],
  },
  {
    name: 'Blockchain & Web3',
    description: 'Build decentralized applications and smart contracts',
    icon_emoji: '⛓️',
    color_class: 'bg-yellow-50 border-yellow-200 hover:border-yellow-400',
    keywords: [
      'blockchain developer', 'Solidity', 'smart contracts', 'Ethereum', 'Web3.js',
      'DeFi', 'NFT', 'Rust', 'Solana', 'cryptography', 'consensus mechanisms',
      'Hardhat', 'Foundry', 'wallet integration', 'tokenomics',
    ],
  },
  {
    name: 'Robotics & Automation',
    description: 'Design and program robots and automated systems',
    icon_emoji: '🦾',
    color_class: 'bg-slate-50 border-slate-200 hover:border-slate-400',
    keywords: [
      'robotics engineer', 'ROS', 'automation', 'computer vision', 'SLAM',
      'motion planning', 'PLC', 'embedded systems', 'control systems', 'Python',
      'C++', 'simulation', 'sensors', 'actuators', 'manufacturing automation',
    ],
  },
  {
    name: 'Healthcare IT & Bioinformatics',
    description: 'Apply technology to healthcare data, systems, and genomics',
    icon_emoji: '🏥',
    color_class: 'bg-emerald-50 border-emerald-200 hover:border-emerald-400',
    keywords: [
      'health informatics', 'EHR', 'FHIR', 'HL7', 'bioinformatics', 'genomics',
      'clinical data', 'HIPAA', 'medical imaging', 'digital health', 'Python',
      'R', 'drug discovery', 'precision medicine', 'clinical trials',
    ],
  },
  {
    name: 'Financial Technology (FinTech)',
    description: 'Build technology solutions for banking, payments, and investing',
    icon_emoji: '💰',
    color_class: 'bg-amber-50 border-amber-200 hover:border-amber-400',
    keywords: [
      'fintech engineer', 'payments', 'banking API', 'trading systems', 'risk management',
      'fraud detection', 'blockchain', 'compliance', 'Stripe', 'Plaid', 'Python',
      'quantitative finance', 'algorithmic trading', 'financial modeling', 'RegTech',
    ],
  },
  {
    name: 'Game Development',
    description: 'Create interactive games and real-time 3D experiences',
    icon_emoji: '🎮',
    color_class: 'bg-violet-50 border-violet-200 hover:border-violet-400',
    keywords: [
      'game developer', 'Unity', 'Unreal Engine', 'C#', 'C++', 'game design',
      '3D graphics', 'shader programming', 'physics engine', 'multiplayer',
      'mobile games', 'VR/AR', 'game AI', 'level design', 'optimization',
    ],
  },
  {
    name: 'Systems Architecture & Infrastructure',
    description: 'Design large-scale distributed systems and enterprise architecture',
    icon_emoji: '🏗️',
    color_class: 'bg-zinc-50 border-zinc-200 hover:border-zinc-400',
    keywords: [
      'solutions architect', 'enterprise architecture', 'distributed systems',
      'high availability', 'scalability', 'database design', 'system design',
      'microservices', 'event-driven', 'message queues', 'caching', 'Linux',
      'network architecture', 'load balancing', 'fault tolerance',
    ],
  },
  {
    name: 'AI Ethics & Governance',
    description: 'Ensure responsible, fair, and transparent AI deployment',
    icon_emoji: '⚖️',
    color_class: 'bg-rose-50 border-rose-200 hover:border-rose-400',
    keywords: [
      'AI ethics', 'responsible AI', 'AI governance', 'fairness', 'bias mitigation',
      'explainability', 'model auditing', 'policy', 'regulatory compliance',
      'privacy', 'AI safety', 'algorithmic transparency', 'GDPR', 'AI policy',
    ],
  },
  {
    name: 'Quantitative Research',
    description: 'Apply mathematical and statistical models to financial and scientific problems',
    icon_emoji: '📈',
    color_class: 'bg-lime-50 border-lime-200 hover:border-lime-400',
    keywords: [
      'quantitative analyst', 'quant researcher', 'Python', 'R', 'C++',
      'stochastic calculus', 'derivatives pricing', 'portfolio optimization',
      'time series', 'machine learning', 'Monte Carlo', 'factor models',
      'backtesting', 'statistical arbitrage', 'risk modeling',
    ],
  },
  {
    name: 'Technical Project Management',
    description: 'Lead engineering teams and deliver complex technical projects',
    icon_emoji: '🗂️',
    color_class: 'bg-cyan-50 border-cyan-200 hover:border-cyan-400',
    keywords: [
      'technical program manager', 'TPM', 'engineering manager', 'project management',
      'agile', 'scrum master', 'risk management', 'stakeholder management',
      'SDLC', 'Jira', 'delivery management', 'technical leadership', 'roadmap',
      'resource planning', 'cross-functional teams',
    ],
  },
  {
    name: 'Computer Vision & NLP',
    description: 'Build systems that see, understand, and generate human language and images',
    icon_emoji: '👁️',
    color_class: 'bg-fuchsia-50 border-fuchsia-200 hover:border-fuchsia-400',
    keywords: [
      'computer vision', 'NLP', 'image recognition', 'object detection', 'BERT',
      'GPT', 'transformers', 'OpenCV', 'semantic segmentation', 'text classification',
      'OCR', 'speech recognition', 'generative AI', 'diffusion models', 'multimodal',
    ],
  },
  {
    name: 'Digital Marketing & Growth',
    description: 'Drive user acquisition and engagement through data-driven marketing',
    icon_emoji: '📣',
    color_class: 'bg-orange-50 border-orange-200 hover:border-orange-400',
    keywords: [
      'growth engineer', 'marketing analytics', 'SEO', 'SEM', 'A/B testing',
      'conversion optimization', 'user acquisition', 'email marketing', 'attribution',
      'Google Analytics', 'SQL', 'Python', 'paid media', 'growth hacking', 'retention',
    ],
  },
];
